title: Site Config
icon: settings

fields:
  role:
    label: "Designer Role"
    type: text
    width: 1/3
  instagram:
    label: "Instagram"
    type: url
    width: 1/3
  email:
    label: "Email"
    type: email
    width: 1/3
  bio:
    label: "Biography"
    type: textarea